### PR TITLE
Feature/fix console jshint

### PR DESCRIPTION
**Pull request by clemens-tolboom**
It is hard to get debugging code in. I'm not sure this is best as it would be preferred not to `console.log()` on production?
- [ ] add `alert()` too?

### CODE REVIEW

**Comment by star-szr** [comment]
Thanks for this @clemens-tolboom! I agree we need something like this and I'm not really sure what's in place currently but I think we'd want something like a debug level, how are similar projects handling this? It would be nice to have a debug function that we can use liberally for logging, and for production it wouldn't do anything.

**Comment by markhalliwell** [comment]
The easiest way to get around this is to use `window.console` or `window.alert`. There is no need to add these to `.jshintrc`. Also, Dreditor has a built-in `$.debug` function: https://github.com/dreditor/dreditor/blob/1.x/src/js/extensions/debug.js

**Comment by clemens-tolboom** [comment]
fair enough ... we should document this for casual users like me. I was quit puzzled this morning as other globals were available but that was due to the settings all ready defined in grunt.js

**Comment by clemens-tolboom** [comment]
Just a note: `$.debug` is not available for unit tests unless added `debug.js` explicit.

**Comment by markhalliwell** [comment]
Correct

**Pull request closed without merging**
