### PR TITLE
Fixed #108: Remove obsolete self-update version check.

### LINKED ISSUE #108: dreditor.org asks you to visit dreditor.org
When I visit dreditor.org with an out of date version of dreditor, I get a popup asking me if I want to visit dreditor.org so I can update (which I'm already doing). This is a useful check on drupal.org, but should be disabled for dreditor.org.

### PR DESCRIPTION
**Pull request by sun**
Browsers have a built-in update mechanism for extensions, so this is unnecessary now.

### CODE REVIEW

**Comment by markhalliwell** [comment]
Firefox doesn't self update as it's only hosted on dreditor.org, not addons.mozilla.org. We can discuss this more tomorrow (history behind why this still exists).

Typos courtesy of Siri

**Comment by sun** [comment]
Oh. Interesting. Though perhaps not worth to keep just for FF? — But yeah, let's discuss tomorrow :)

**Comment by markhalliwell** [comment]
To remove this, we'll need to provide an [updateURL](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#updateURL) in the FF extension manifest

We'll also need to create an [updateKey](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#updateKey) using the [McCoy](https://developer.mozilla.org/en-US/docs/McCoy) CLI tool.

We'll also likely need to configure https://dreditor.org to serve this [update.rdf](https://developer.mozilla.org/en-US/docs/Extension_Versioning,_Update_and_Compatibility#Update_RDF_Format) manifest appropriately.

I'm sure this won't change if we were to use jpm (#130).

**Comment by markhalliwell** [comment]
Postponed on #156

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#63

**Pull request closed without merging**
