### PR TITLE
Add button to insert remaining tasks

### PR DESCRIPTION
**Pull request by star-szr**
See https://drupal.org/node/2236363.

Tested Chrome and Firefox, I was unable to test Safari for some reason:

```
grunt build:safari
Running "exec:build_safari_ext" (exec) task
>> Exited with code: 127.
>> Unable to create release/safari/dreditor.safariextension
Warning: Task "exec:build_safari_ext" failed. Use --force to continue.

Aborted due to warnings.
```

### CODE REVIEW

**Comment by sun** [comment]
Can we rename the button into "Novice template"?
(ditto for the plugin filename; `issue.novice.template.js`)

When adding another button, I'd also like to remove the "Insert" prefix from the existing button.

Lastly, the additional class name on the button looks bogus to me; that should be solved differently.

**Comment by star-szr** [comment]
Well this isn't really Novice template, it's not a whole IS template, it's just a list of remaining tasks with links to contributor docs.

I'm open to ideas for how else to insert this button after the existing button other than adding a class but this seemed like the most solid approach to me, otherwise I was trying to target a text node containing `(` or basing things off the text content of the button which can easily change. I tried to make a BEM-y class name.

**Comment by YesCT** [comment]
Yeah, it's not the whole template. So I think naming it remaining tasks is good.

I think taking off the insert is a good idea.

**Comment by star-szr** [comment]
Here's the template node: https://drupal.org/node/2272209

**Comment by sun** [comment]
1. In that case, let's rename the button label to "Novice tasks"
   
   I guess I was confused, because I've seen a range of novice issues very recently that happened to use a specialized template (including a big fat warning at the top that more experienced contributors should not touch the issue) — thus wondering whether it wouldn't make more sense to provide a button to insert that full template _by default_ (including all the tasks)…? - If you only need the tasks, then you can remove the other stuff yourself?
2. If we need multiple different buttons in a certain spot, then there are two choices:
   1. Create an abstract base processing plugin that only injects a _DIV container_ (the spot) into which buttons can be appended to.
   2. Merge the two buttons into a single plugin and make that plugin inject all buttons (give or take a wrapping container).
   
   For the sake of simplicity, I'd prefer the latter, but would recommend to split the button operations into separate methods on the behavior object (next to `attach()`); i.e., `insertSummaryTemplate()` + `insertNoviceTasksTemplate()`.
   
   Come to think of it, combining both into a single plugin also helps to prevent duplicate code, since we can abstract all common functionality into separate helper methods.

**Comment by YesCT** [comment]
**
1.
The _do not do this if you are not a novice_ does not have as much consensus as the contributor tasks do. I'd prefer to let people still add that warning to their issues on their own.

_I_ would be ok with adding the remaining tasks to the issue summary template.. But with the austin sprint looming so soon, and mentors needed to update issues _before_ that, 
I dont want to get side tracked on making frequent issue queue users mad who then have to delete that section. Perhaps in a while, people will start complaining that they have to click two buttons, and then we will know _everyone_ is ready for the contributor tasks to be in the template.

I'm not so sure about the label "novice tasks" since these are not all novice tasks, but really just listing out common contributor tasks and instructions for how to do them.
If others feel strongly about the label being novice tasks, I'm ok with that though.

**
2. ii. seems fine to me.. And that is a change in the underlying implementation, not a change in how it would look to dreditor users, correct? Is it possible we can get this in now, and then do 2. ii. in a followup issue? ([update:] I opened https://github.com/dreditor/dreditor/issues/163)

**Comment by sun** [comment]
Alrighty.  As this branch lives in the dreditor repo, I took the liberty to implement and incorporate the changes that I suggested myself - hope that's OK with you @Cottser.

_Background: @markcarver and I recently discussed that public feature branches in the dreditor repo are actively meant to be collaborated on (as opposed to PRs/branches from user-specific forks, for which it is possible to create PRs [against a PR], but that's cumbersome and thus rather rare…)_
1. Merged the new plugin into the existing issue.summary.template plugin.
2. Move the per-button code execution into separate methods.
3. Additionally cleaned up the overly verbose link to the _issue summary instructions_ page.

Screenshot:

dreditor-novice-tasks

**Comment by YesCT** [comment]
I went to install the build from this (cause I noticed a create commit message button problem with an earlier build of this issue) and .. it wont let me install it. I drag it into the extensions settings page, but it just opens the file, like viewing source of it or something...

**Comment by YesCT** [comment]
commit message button not working is not related to changes on this issue.
so I opened https://github.com/dreditor/dreditor/issues/164

**Comment by markhalliwell** [comment]
Chrome builds from https://dreditor.org/development/build are currently only served as a `zip` archive, must be extracted and then installed manually:
load

FWIW, we're working on making this a single click install once we can properly package them as `crx` extensions: #140.

**Comment by markhalliwell** [comment]
Also, please make sure you're either 1) testing these builds in a separate browser profile (ie: like one setup just for dreditor development) or 2) disable/uninstall the current released extension.

**Comment by YesCT** [comment]
I had to drag the whole unzipped folder! (I was just dragging the .js) 
thanks.

**Comment by markhalliwell** [comment]
**RTBC**

**Comment by star-szr** [comment]
Thanks all :)

**Pull request merged**
