### PR TITLE
Add button to insert Drupal 8 beta evaluation criteria

### LINKED ISSUE #233: Button to insert beta phase evaluation
See: 
https://www.drupal.org/core/beta-changes
https://www.drupal.org/node/2373483

We should add a button to Dreditor to insert the beta phase evaluation template in https://www.drupal.org/node/2373483 so that contributors can easily fill out the table. We originally were going to add it to the issue summary template, but since most issues that need evaluation exist already and only Drupal 8 core issues need the table, it would be better UX to have a separate button.

### PR DESCRIPTION
**Pull request by star-szr**
Fixes #233.

### CODE REVIEW

**Comment by markhalliwell** [comment]
This needs a condition to only show when on a core issue (as this is what the button pertains to).

**Comment by star-szr** [comment]
Okay, I'll look into that this evening.

**Comment by star-szr** [comment]
Now checking against the project and only adding the button for 'drupal'. I squashed that in and revised the commit message slightly.

**Comment by star-szr** [comment]
I re-ran the Travis test today, Phantomjs timed out so sort of a random fail.

**Comment by markhalliwell** [comment]
@xjm or @YesCT, https://dreditor.org/development/build has this PR for y'all to test. Let me know if this is what you were thinking and if so, I'll merge.

**Comment by markhalliwell** [comment]
@xjm is on vacation. I just tested this and it appears correctly. Any changes can now be made on the d.o "template" itself if needed.

**Pull request merged**
