### PR TITLE
Clone button does not work in Chrome

### LINKED ISSUE #180: d.o issue comment updates broke clone button

### PR DESCRIPTION
**Pull request by markhalliwell**
Fixed #180

Originally, this did not put the original issue's body or title. However, in hind-sight, this button is for "cloning" and issue. I also took out the `Follow-up to: [#N]` bit since we can now add the parent relationship.

### CODE REVIEW

**Comment by markhalliwell** [comment]
Also, I removed the whole `setTimeout` crap and now using proper window event binding.

**Comment by sun** [comment]
Hm.  When I added the issue title + parent issue relationship in #132, I intentionally did not add the issue summary/body, because that's a lot of text you'd have to delete + replace manually.  I do not think it makes sense to clone the body text.

Also, while the parent issue relationship is prepopulated now, it is still common practice to state the _"Follow-up to: …"_ line in the issue summary — primarily because the relationships only appear in the sidebar and are not immediately recognized by readers.

Not sure how a native event listener would work better than jQuery.ready().  I'd like to test that change, since apparently, the clone feature seems to have worked for people having a fast connection to d.o.

FWIW, I'm not able to reproduce #180

**Comment by markhalliwell** [comment]
> I intentionally did not add the issue summary/body

From https://github.com/dreditor/dreditor/commit/760edf41d6c9559d915936e2c73d675d41732026:

``` diff
- $doc.find('#edit-body-und-0-value').val('Follow-up from [#' + Drupal.dreditor.issue.getNid() + '].\n\n');
+              sel = '#edit-body-und-0-value';
+              var oldid = Drupal.dreditor.issue.getNid();
+              $newform.find(sel)
+                .val('Follow-up to [#' + oldid + ']\n\n' + $oldform.find(sel).val());
```

> Also, while the parent issue relationship is prepopulated now, it is still common practice to state the "Follow-up to: …" line in the issue summary — primarily because the relationships only appear in the sidebar and are not immediately recognized by readers.

I'm ok with adding this back in, was just trying to separate the ideas behind what a "clone" is and what a "Follow-up" (#184) is.

> Not sure how a native event listener would work better than jQuery.ready(). I'd like to test that change, since apparently, the clone feature seems to have worked for people having a fast connection to d.o.
> 
> FWIW, I'm not able to reproduce #180

I added comments explaining what the reasoning behind this is. FWIW, @YesCT and I both use Macs/Chrome and can reproduce this every time. It could be the combination of Chrome, Mac, jQuery 1.4.4 on d.o:

``` diff
+          // @todo Revisit this once Dreditor no longer depends on d.o's jQuery.
+          // $(w).bind('load') does not actually bind to the new window "load"
+          // event. This may be on purpose or a bug with the currently used
+          // jQuery version on d.o (1.4.4).
```

**Comment by markhalliwell** [comment]
xref #156 (for `@todo` followup)

**Pull request merged**
