### PR TITLE
Introduce grunt into CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by clemens-tolboom**
Add a `DON'T PANIC` first line :)

### CODE REVIEW

**Comment by clemens-tolboom** [comment]
This could still use some more explanation about
1. How to 'navigate' through the source tree. Maybe add a DIR TREE?
2. How to write tests

**Comment by sun** [comment]
Great to see progress on the modularization! :)

That said, I'm a bit confused -- this change has been merged into `1.x`, but wasn't the idea to perform this major rewrite in `2.x` (or `master`)?

**Comment by markhalliwell** [comment]
Originally, yes, I started doing all of this work on 2.x. However the more I thought about it, there really wouldn't be much difference between the final script of 1.x and 2.x (from a feature/functionality/release standpoint). This didn't really make sense for semantic versioning. I'd rather leave 2.x for an actual rewrite of the code/features/ui. This was just reorganization into smaller files so it's more manageable and introducing the automation of grunt to compile the extensions properly.

**Comment by clemens-tolboom** [comment]
As a contributor I'm very happy with this change of workflow. It's harder to get started but code is more adjustable by smaller file size and `grunt watch` ... also the browser dependencies are abstracted away. YEAH

**Pull request merged**
