### PR TITLE
Formalize the public feature/topic branch policy

### PR DESCRIPTION
**Pull request by sun**
We recently discussed a range of aspects around public feature/topic branches on IRC.

In general, I'm not a fan of too much bureaucracy/overhead, but formalizing these discussion points would probably help us to move forward on some of the bigger topics in a more controlled way.

Partially using IETF/RFC terminology for clarity.

This initial PR represents my own understanding only.  It is meant to supply a concrete rubbing surface for further discussion, so if you disagree, please consider to disagree wisely and sensibly. :heart:

### CODE REVIEW

**Comment by markhalliwell** [comment]
I really don't disagree with this per se.

However, I would say that this should probably be in a new/separate file called `WORKFLOW.md` mayhaps.

**Comment by markhalliwell** [comment]
Actually I think a lot of `CONTRIBUTING.md` could be split up so it's not just one huge file. Also, with these new files, should we perhaps add a `/documentation` sub-folder?

**Comment by sun** [comment]
Hm.  A ToC in a sidebar (like http://getbootstrap.com/components) would certainly help.

But otherwise, I think that >95% of the current content is super-relevant for the topic of how to contribute.  I'd defer a potential split until there's more...

FYI, just added a commit with some minor clarifications.

**Comment by markhalliwell** [comment]
Ok, well in that case. I think this should be one of the first things (at the top) people see before getting into the grunt stuff (not in between the "automated" and "manual" testing anyway).

**Comment by markhalliwell** [comment]
I think we should also create and follow branch naming conventions (similar to http://nvie.com/posts/a-successful-git-branching-model/):
`issue/N` - a fix for `N` issue number
`feature/whatever_you_want` - Name the branch whatever you want, just under a `feature/` sub-dir.

**Comment by sun** [comment]
I'd recommend to move forward in smaller baby steps.
1. The new chapter has been placed into a natural/logical location for now:  Before the topic of public/private branches even matters in any way, you need to have a fully working local development environment.
   As far as I understood the current outline, the _Manual testing_ chapter is separated into an own section, because it also matters if you're just testing changes (but not hacking).
2. There's no point in trying to rule branch names in forks of contributors, so the topic of branch names only applies to public feature branches in the dreditor repo itself.  While I can see some merit behind that idea, a few considerations:
   1. We do not have sufficient data to draw a pattern/conclusion yet.
   2. Branches with a `/` (slash) in their name are not fully supported by all git tools/UIs, so I'd be cautious with using that delimiter.
   3. Public bug-fix branches are almost always going to live and die very quickly anyway, so I personally don't really care whether they're named `chocolate-chips` or `fix-1234` — in fact, I'd prefer descriptive names at all times, so that I don't have to consult my browser to look up what the heck _1234_ means.  `chocolate-chips` immediately tells me that it's about _chocolate chips_, so if I'm seeking for _ice cream_, I can ignore that option.
   4. With regard to the intended scope, we should rather think about language than syntax/structure; e.g.:
      1. Is `chrome-autoload` acceptable or should it be `autoload-chrome` or `grunt-watch-chrome`?
      2. Are abbreviations acceptable?  `di` vs. `dependency-injection`
      3. Child topics of major features?  `plugin-di` is a child of `plugin`…?

Perhaps we can move the discussion on (2) names of public branches into a separate issue?

**Comment by markhalliwell** [comment]
Sure, sounds good.

**Pull request merged**
