### PR TITLE
Disabled the drupal.org update check

### PR DESCRIPTION
**Pull request by davereid**
This fixes issue #8

### CODE REVIEW

**Comment by markhalliwell** [comment]
I'm going wait on this one for now. I need to see how updates in general are going to work (automatically) for other browsers (ie: safari, firefox) and probably have to implement some sort of update url too.

**Comment by davereid** [comment]
Yeah, I figure in the meantime we should just not make the call home to drupal.org if it's not accurate. I left in the code that does the update check, but it feels wise not to have it be actually run until the better update checking is implemented.

**Comment by markhalliwell** [comment]
Yes, except the next "update" will actually be the 1.2.1 (2.0.0-rc1) milestone, which I have already planned to refactor the entire "update" process in preparation for the 2.0 release. I think having #8 is fine and we could probably just close this PR for now.

**Comment by davereid** [comment]
I still don't see the value in not disabling the check in the meantime. Oh well.

**Comment by sun** [comment]
I agree with @davereid — there's no point in checking the drupal.org commit log page for updates anymore.

We should not only comment out the function call, we should rip out the entire function.  The new implementation will look completely different anyway.

**Comment by markhalliwell** [comment]
I don't _disagree_ with @davereid at all. I just have plans to make sure that there is some sort of "update" notification in place when we eventually switch to real extensions. Even though, yes, there's a "chrome extension" and currently on the Chrome Web Store, it will eventually actually be hosted/served from dreditor.org. All browser extensions have the ability to specify an "update_url" (ie: https://github.com/dreditor/dreditor.org/blob/7.x/update.plist for safari). We need update feeds in place for all extensions (chrome, ff, opera). I will see what I can do this weekend to get this sorted out (even if it's a manual implementation, temporarily).

**Pull request closed without merging**
