### PR TITLE
Reduce noise of travis-ci IRC bot

### PR DESCRIPTION
**Pull request by sun**
Only send one message per build.

### CODE REVIEW

**Comment by markhalliwell** [comment]
The reason this is like this is to see the "build passed/failed" on it's own line at the beginning instead of having to find it half way through.

:-1:

**Comment by sun** [comment]
Hm. The suggestion here improves readability by reducing clutter + making notices more easy to parse:

``` diff
-[travis-ci] Build #219 (dreditor/dreditor/1.x):
-[travis-ci] - The build passed. (http://travis-ci.org/dreditor/dreditor/builds/26004428)
+[travis-ci] #219: dreditor/dreditor/1.x: The build passed. → http://travis-ci.org/dreditor/dreditor/builds/26004428
```

**Comment by markhalliwell** [comment]
I suppose your IRC client doesn't wrap messages (or is more likely on a screen that's huge)?

**Comment by markhalliwell** [comment]
I'll deal.

**Comment by sun** [comment]
For posterity:

The → character in the template caused travis-ci to stall.  Even though the `.travis.yml` file is correctly encoded in UTF-8.  Removing the character fixed the problem (and travis-ci automatically resurrected builds).

Known issue: travis-ci/travis-ci#1376

**Comment by sun** [comment]
We also replaced %message with %result (which could/should be travis-ci's default).

And we additionally removed the %repository, because for Dreditor, _There can only be one._

``` diff
-[travis-ci] Build #219 (dreditor/dreditor/1.x):
-[travis-ci] - The build passed. (http://travis-ci.org/dreditor/dreditor/builds/26004428)
+[travis-ci] #219 1.x passed: http://travis-ci.org/dreditor/dreditor/builds/26004428
```

``` yml
    template:
      - "#%{build_number} %{branch} %{result}: %{build_url}"
```

**Comment by sun** [comment]
@markcarver created travis-ci/travis-ci#2363 to hopefully get rid of the (currently enforced/hard-coded) `[travis-ci]` prefix in all messages.

**Pull request merged**
