### PR TITLE
Add grunt-contrib-watch

### PR DESCRIPTION
**Pull request by clemens-tolboom**

### CODE REVIEW

**Comment by sun** [comment]
`watch` is listed in `optionalDependencies` just a few lines below already.  Listing a dependency more than once is invalid.

However, it is possible that we misinterpreted the purpose of `optionalDependencies` to work similar to suggested Composer dependencies (prompted to be installed on demand), which doesn't appear to be the case if I'm interpreting the manual & various blog posts correctly.

From https://coderwall.com/p/rmosmg/npm-package-json-optionaldependencies

> Initially I thought that the packages in the `optionalDependencies` section would not be installed automatically (at least for a production install). This is in fact not the case. An install is attempted, it's just that failure is package install failure is tolerated...

**Comment by clemens-tolboom** [comment]
I missed the optionalDependencies section.

But why not add it to the dependencies ... an extra grunt command does not harm and help others getting started.

**Comment by markhalliwell** [comment]
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Comment by subhojit777** [comment]
This issue was moved to dreditor/dreditor#62

**Pull request closed without merging**
